# Generated by Django 6.1 on 2026-09-08 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='passengers',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='seat',
            table='seats',
        ),
        migrations.AlterModelTable(
            name='station',
            table='stations',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
        migrations.AlterModelTable(
            name='train',
            table='trains',
        ),
        migrations.AlterModelTable(
            name='wagon',
            table='wagons',
        ),
    ]
